#!/bin/sh

. ./zargon.cfg

PATH=.:$PATH

# end the keyphrase listener on exit
if [ "$1" = "-k" ]
then
    if [ -f $ZLISTEN_PIDFILE ]
    then
	echo "cleaning up"
	kill $(cat $ZLISTEN_PIDFILE)
	rm -f $ZLISTEN_PIDFILE
    fi
    exit
fi
trap "$0 -k; exit" QUIT INT TERM EXIT

rm -f $ZLISTEN_PIDFILE

while true
do
    # https://stackoverflow.com/a/39401963/361413
    (unbuffer pocketsphinx_continuous -inmic yes -keyphrase "$ZLISTEN_KEYPHRASE" -kws_threshold "\1e-15" -logfn /dev/null &  echo $! > $ZLISTEN_PIDFILE; wait) | \
    while read LINE
    do
	echo $LINE
	case "$LINE" in
	    *"$ZLISTEN_KEYPHRASE"*)
	    echo "found keyword"
	    # don't run keyphrase listener while we record user input
	    kill $(cat $ZLISTEN_PIDFILE)
	    zsay "$ZLISTEN_PROMPT"
	    # https://unix.stackexchange.com/a/57593/80396
	    rec zrecording.flac rate 32k silence 1 0.1 3% 1 3.0 3%
	    zsay "$ZLISTEN_ACK"
	    play zrecording.flac
	    ;;
	esac
    done
done
